ejercicios_csura/Semana05/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Semana05.Models
{
    public class Libro
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
    }
}

ejercicios_csura/Semana05/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Semana05.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ejercicios_csura/Semana05/Controllers/LibroController.cs
using Semana05.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Semana05.Controllers
{
    public class LibroController : Controller
    {
        List<Libro> libros = new List<Libro>()
        {
            new Libro { Id = 1, Titulo = "El Camino De Los Reyes", Autor = "Brandon Sanderson" },
            new Libro { Id = 3, Titulo = "Los Pilares De La Tierra", Autor = "Ken Follett" },
            new Libro { Id = 2, Titulo = "Cien años de soledad", Autor = "Gabriel García Márquez" },
            new Libro { Id = 4, Titulo = "1984", Autor = "George Orwell" },
            new Libro { Id = 5, Titulo = "Orgullo y prejuicio", Autor = "Jane Austen" },
        };

        // GET: Libro
        public ActionResult Index()
        {
            return View(libros);
        }

        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                foreach (var libro in libros)
                {
                    if (libro.Id == id)
                    {
                        return View(libro);
                    }
                }
            }
            return HttpNotFound();
        }
    }
}

ejercicios_csura/Semana05/Controllers/SaludoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Semana05.Controllers
{
    public class SaludoController : Controller
    {
        // GET: Saludo
        public ActionResult Index()
        {
            ViewBag.MensajeDelControlador = "Este mensaje viene del controlador.";
            return View();
        }
    }
}

ejercicios_csura/Semana05/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

ejercicios_csura/Semana05/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

ejercicios_csura/Semana05/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

ejercicios_csura/Semana05/Views/Libro/Details.cshtml
@model Semana05.Models.Libro

@{
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Libro</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Titulo)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Titulo)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Autor)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Autor)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id } , new { @class = "btn btn-warning" }) |
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-dark" })
    </p>
</body>
</html>

ejercicios_csura/Semana05/Views/Libro/Index.cshtml
@model IEnumerable<Semana05.Models.Libro>

@{
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @*<p>
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
    </p>*@
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Autor)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.Id } , new { @class = "btn btn-info" })*@ |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.Id } , new { @class = "btn btn-danger" })*@
                </td>
            </tr>
        }
        <tr>
            <td>
               Prueba
            </td>
            <td>
               Error 404
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = 100 }, new { @class = "btn btn-info" })*@ |
                @Html.ActionLink("Details", "Details", new { id = 100 }, new { @class = "btn btn-warning" }) |
                @*@Html.ActionLink("Delete", "Delete", new { id = 100 }, new { @class = "btn btn-danger" })*@
            </td>
        </tr>

    </table>
</body>
</html>

ejercicios_csura/Semana05/Views/Saludo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        <h2>Página de Saludo</h2>
        <p>@ViewBag.MensajeDelControlador</p>
    </div>
</body>
</html>

ejercicios_csura/Semana05/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Libros", "Index", "Libro", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>